import { DiscussionCard } from '../types';

export const discussionCards: DiscussionCard[] = [
  {
    id: '1',
    sentiment: 'bullish',
    title: 'Swire (19 HK / 87 HK) Announces NEW, Bigger,...',
    body: 'After announcing its FY25 results, Swire Pacific (A) (19 HK) said it was placing out 2.52% in Cathay Pacific Airways (293 HK) @HK$11.74/share, reducing its stake to ~42.46%; and the Air China/CNAHC/Swire collective holding to ~72.44%. Will follow up more on this later.',
    author: { initials: 'DB', name: 'David Blennerhassett', gradientFrom: '#3b82f6', gradientTo: '#6366f1' },
    time: '5 minutes ago',
    impressions: 1,
  },
  {
    id: '2',
    sentiment: 'bearish',
    title: 'Dongfeng (489 HK): On VOYAH\'s Imminent Spi...',
    body: 'Li Auto (2015 HK) FY25 net profit declined 86% yoy to RMB1.1bn amid heightened industry competition. Dongfeng (489 HK): Revisiting VOYAH\'s Spin-Off Valuation & Dongfeng (489 HK): Questioning The EV Listing Valuation',
    author: { initials: 'DB', name: 'David Blennerhassett', gradientFrom: '#3b82f6', gradientTo: '#6366f1' },
    time: '16 minutes ago',
    impressions: 0,
  },
  {
    id: '3',
    sentiment: 'bullish',
    title: 'Golden Entertainment\'s Controversial Buyout: ...',
    body: 'I voted against everything. I read the proxy statement and thought the sale process extremely flawed or potentially rigged and harmful to shareholder interests. It started from Santander advising Golden\'s board on exploring strategic alternatives and then switching to advising the CEO on his...',
    author: { initials: 'AU', name: 'Anonymous User', gradientFrom: '#475569', gradientTo: '#64748b' },
    time: 'a day ago',
    impressions: 0,
    replies: [
      {
        id: 'r1',
        body: '100% agree that this is a rigged process (implies a way too cheap price also), voting against as well. I seriously doubt we\'ll get a higher offer but the limited downside is still appealing.',
        author: { initials: 'AU', name: 'Anonymous User', gradientFrom: '#475569', gradientTo: '#64748b' },
        time: '18 hours ago',
      }
    ],
  },
  {
    id: '4',
    sentiment: 'bearish',
    title: 'Docebo Announces $60M Odd-Lot Tender Off...',
    body: 'Yesterday was nuts. Back to earth today.',
    author: { initials: 'AU', name: 'Anonymous User', gradientFrom: '#475569', gradientTo: '#64748b' },
    time: '12 hours ago',
    impressions: 0,
  },
  {
    id: '5',
    sentiment: 'bullish',
    title: 'Korean Re: Cancellation of 9.3% of Outstandin...',
    body: 'It has been 10 years since the late Chairman of Korean Re Won Hyuk-Hee passed away. His two sons have...',
    author: { initials: 'DK', name: 'Douglas Kim', gradientFrom: '#f59e0b', gradientTo: '#fbbf24' },
    time: '13 hours ago',
    impressions: 2,
  },
  {
    id: '6',
    sentiment: 'bearish',
    title: 'Korea Zinc\'s Plans to Improve Corporate Gov...',
    body: 'Independent board seats + audit committee reform. MBK pressure finally producing results. Long-term structural positive for minority shareholders.',
    author: { initials: 'DK', name: 'Douglas Kim', gradientFrom: '#f59e0b', gradientTo: '#fbbf24' },
    time: '14 hours ago',
    impressions: 5,
  },
  {
    id: '7',
    sentiment: 'bullish',
    title: 'TSMC N2 Yield Ramp — Better Than Expected...',
    body: 'Channel checks pointing to 60%+ N2 yield in January. If confirmed on the April earnings call, consensus EPS needs a significant lift. Key beneficiaries: Apple, NVIDIA next-gen.',
    author: { initials: 'AK', name: 'Anil Kumar', gradientFrom: '#00b386', gradientTo: '#6366f1' },
    time: '2 hours ago',
    impressions: 8,
  },
  {
    id: '8',
    sentiment: 'neutral',
    title: 'DBS Group Q4 2025 — NIM Resilience Surprises...',
    body: 'Better deposit mix than peers meant NIM only compressed 4bps vs 12bps feared. Dividend upgrade seems increasingly likely heading into FY2026.',
    author: { initials: 'SP', name: 'Sunil Prakash', gradientFrom: '#10b981', gradientTo: '#00c896' },
    time: '3 hours ago',
    impressions: 3,
  },
];
