import { FeedItem } from '../types';

export const feedItems: FeedItem[] = [
  {
    id: '1',
    sentiment: 'bearish',
    ticker: '005930 KS',
    title: 'HBM3E Qualification Timeline Slips Again — Supply Glut Risk Emerging',
    excerpt: 'Our channel checks suggest Samsung\'s HBM3E qualification at NVIDIA has slipped by another 4-6 weeks, pushing meaningful revenue contribution to Q3 at the earliest.',
    author: { initials: 'NK', name: 'Nader Khouri', gradientFrom: '#3b82f6', gradientTo: '#8b5cf6' },
    time: '2h',
    views: 312,
  },
  {
    id: '2',
    sentiment: 'bullish',
    ticker: 'SIA SP',
    title: 'Singapore Airlines: Premium Cabin Load Factors Hit 5-Year High',
    excerpt: 'Business class load factors exceeded 82% in February, the highest since 2019. Yield management improvements driving 12% revenue per ASK growth.',
    author: { initials: 'RK', name: 'Raghav Kapoor', gradientFrom: '#7c3aed', gradientTo: '#a78bfa' },
    time: '3h',
    views: 198,
  },
  {
    id: '3',
    sentiment: 'neutral',
    ticker: 'DBS SP',
    title: 'DBS Group Q4 2025 — NIM Resilience Surprises, But Loan Growth Disappoints',
    excerpt: 'NIM compressed only 4bps vs 12bps feared, but loan growth came in at 2.1% vs consensus 4.3%. Dividend upgrade still on the table.',
    author: { initials: 'SP', name: 'Sunil Prakash', gradientFrom: '#10b981', gradientTo: '#00c896' },
    time: '4h',
    views: 445,
  },
  {
    id: '4',
    sentiment: 'bullish',
    ticker: 'TSM US',
    title: 'TSMC N2 Yield Ramp Tracking Ahead — Consensus EPS Needs a Lift',
    excerpt: 'Channel checks pointing to 60%+ N2 yield in January. Key beneficiaries: Apple next-gen, NVIDIA Blackwell successor.',
    author: { initials: 'AK', name: 'Anil Kumar', gradientFrom: '#00b386', gradientTo: '#6366f1' },
    time: '5h',
    views: 621,
  },
  {
    id: '5',
    sentiment: 'bearish',
    ticker: '2015 HK',
    title: 'Li Auto FY25 Net Profit Collapses 86% on Competition',
    excerpt: 'Net profit fell to RMB1.1bn amid brutal EV price war. Margin trajectory now structurally challenged without new premium SKUs.',
    author: { initials: 'DB', name: 'David Blennerhassett', gradientFrom: '#3b82f6', gradientTo: '#6366f1' },
    time: '6h',
    views: 289,
  },
  {
    id: '6',
    sentiment: 'bullish',
    ticker: '005930 KS',
    title: 'Timing for Samsung Electronics KRW 3.2tn Block: Next Thursday',
    excerpt: 'Our analysis of the disclosed schedule points to block execution around March 20. Institutional buyers likely pre-positioned.',
    author: { initials: 'DK', name: 'Douglas Kim', gradientFrom: '#059669', gradientTo: '#34d399' },
    time: '8h',
    views: 167,
  },
  {
    id: '7',
    sentiment: 'neutral',
    ticker: 'GLXY US',
    title: 'Galaxy Digital: US Index Inclusion Following Reorganization',
    excerpt: 'Post-redomiciliation, GLXY becomes eligible for Russell 3000 inclusion. Passive demand estimated at $180-220M.',
    author: { initials: 'DI', name: 'Dimitris Ioannidis', gradientFrom: '#6366f1', gradientTo: '#8b5cf6' },
    time: '9h',
    views: 334,
  },
  {
    id: '8',
    sentiment: 'bullish',
    ticker: 'AMZN US',
    title: 'Beyond Chips and Capex: Private Credit in the AI Ecosystem',
    excerpt: 'Amazon\'s quiet $4bn AI infrastructure debt facility signals a new financing paradigm. Private credit is becoming the hidden fuel of the AI buildout.',
    author: { initials: 'RV', name: 'Raghav Vashisht', gradientFrom: '#b84a00', gradientTo: '#f97316' },
    time: '11h',
    views: 512,
  },
  {
    id: '9',
    sentiment: 'bearish',
    ticker: '17 HK',
    title: 'We Need To Talk About New World Development',
    excerpt: 'Debt-to-equity now at 1.8x, covenant headroom tightening. Board reshuffle doesn\'t address structural leverage problem.',
    author: { initials: 'DB', name: 'David Blennerhassett', gradientFrom: '#3b82f6', gradientTo: '#6366f1' },
    time: '12h',
    views: 891,
  },
  {
    id: '10',
    sentiment: 'bullish',
    ticker: 'KRZ KS',
    title: 'Korea Zinc: Cancellation of 9.3% of Outstanding Shares',
    excerpt: 'MBK pressure finally producing governance results. Independent board seats + audit committee reform represent long-term structural positive.',
    author: { initials: 'DK', name: 'Douglas Kim', gradientFrom: '#059669', gradientTo: '#34d399' },
    time: '13h',
    views: 203,
  },
  {
    id: '11',
    sentiment: 'neutral',
    ticker: 'RERE US',
    title: 'ATRenew: Continues to Execute Across the Board',
    excerpt: 'Revenue grew 18% YoY, EBITDA margin expanding to 8.2%. Several growth opportunities on the horizon including HK market entry.',
    author: { initials: 'ZS', name: 'Zacks Small Cap', gradientFrom: '#475569', gradientTo: '#64748b' },
    time: '14h',
    views: 156,
  },
  {
    id: '12',
    sentiment: 'bearish',
    ticker: 'DCBO US',
    title: 'Docebo Announces $60M Odd-Lot Tender Offer Amidst Declining Shares',
    excerpt: 'Strategic review ongoing but buyback signals management believes stock undervalued. Enterprise sales cycle lengthening is the real concern.',
    author: { initials: 'AU', name: 'Anonymous User', gradientFrom: '#475569', gradientTo: '#64748b' },
    time: '15h',
    views: 278,
  },
  {
    id: '13',
    sentiment: 'bullish',
    ticker: 'STAAR US',
    title: 'STAAR Surgical: Alcon\'s Revised Bid Signals Floor Valuation',
    excerpt: 'Third bid at $27.50 represents 42% premium to unaffected price. Activist pressure likely pushes this to $30+.',
    author: { initials: 'JM', name: 'James Morrison', gradientFrom: '#06b6d4', gradientTo: '#0891b2' },
    time: '16h',
    views: 445,
  },
  {
    id: '14',
    sentiment: 'neutral',
    ticker: 'UNIQUR US',
    title: 'uniQure Faces FDA Trial Design Challenge Amid Strong Pipeline',
    excerpt: 'FDA requesting additional biomarker endpoints for AMT-130 pivotal trial. Timeline extends 12-18 months but commercial opportunity unchanged.',
    author: { initials: 'PL', name: 'Philippe Laurent', gradientFrom: '#7c3aed', gradientTo: '#c084fc' },
    time: '18h',
    views: 367,
  },
  {
    id: '15',
    sentiment: 'bullish',
    ticker: 'DBS SP',
    title: 'DBS Q4 Beat — Dividend Upgrade Now Base Case for FY2026',
    excerpt: 'Better deposit mix than peers meant NIM only compressed 4bps vs 12bps feared. SGD 2.16 DPS now looks conservative.',
    author: { initials: 'SP', name: 'Sunil Prakash', gradientFrom: '#10b981', gradientTo: '#00c896' },
    time: '1d',
    views: 672,
  },
  {
    id: '16',
    sentiment: 'bearish',
    ticker: '19 HK',
    title: 'Swire Pacific Reduces Cathay Stake to 42.46% via Block Trade',
    excerpt: 'Placing 2.52% at HK$11.74/share. Combined Air China/CNAHC/Swire holding now at ~72.44%. Strategic rationale unclear.',
    author: { initials: 'DB', name: 'David Blennerhassett', gradientFrom: '#3b82f6', gradientTo: '#6366f1' },
    time: '1d',
    views: 523,
  },
  {
    id: '17',
    sentiment: 'neutral',
    ticker: '293 HK',
    title: 'Cathay Pacific: Post-Placement Overhang Analysis',
    excerpt: 'Float increases modestly. Historical patterns suggest 3-6 week absorption period before meaningful upside. Watch July pax data.',
    author: { initials: 'AK', name: 'Anil Kumar', gradientFrom: '#00b386', gradientTo: '#6366f1' },
    time: '1d',
    views: 234,
  },
  {
    id: '18',
    sentiment: 'bullish',
    ticker: 'AVI HK',
    title: 'AviChina: H-Share Discount at 5-Year Wide Despite Improved Fundamentals',
    excerpt: 'A-H spread at 38% vs historical 18-22%. Military modernization budget increase of 7.2% provides multi-year earnings visibility.',
    author: { initials: 'WC', name: 'Wei Chen', gradientFrom: '#003a6b', gradientTo: '#0369a1' },
    time: '2d',
    views: 189,
  },
  {
    id: '19',
    sentiment: 'bullish',
    ticker: 'DFI SP',
    title: 'DFI Retail: Hidden Value in Southeast Asian Convenience Store Network',
    excerpt: '7-Eleven franchise expansion in PH and HK accelerating. Sum-of-parts suggests 35% upside to current price.',
    author: { initials: 'RK', name: 'Raghav Kapoor', gradientFrom: '#7c3aed', gradientTo: '#a78bfa' },
    time: '2d',
    views: 145,
  },
  {
    id: '20',
    sentiment: 'bearish',
    ticker: 'GLX US',
    title: 'Crypto Market Correction Risk: Galaxy Digital Exposure Analysis',
    excerpt: 'BTC down 12% from ATH. Galaxy\'s venture book marks could see 15-20% write-down if crypto winter extends through Q2.',
    author: { initials: 'MH', name: 'Marcus Hill', gradientFrom: '#6b21a8', gradientTo: '#a21caf' },
    time: '2d',
    views: 398,
  },
];
